### ISSUE TITLE
Update readme with instructions to run locally

### ISSUE THREAD

**Issue by ptrelease** [hmcts/adoption-cos-api#903]
### What would you like to change?

Readme

### How do you think that would improve the project?

Allow new devs to run the service locally for development

### If this entry is related to a bug, please provide the steps to reproduce it

These are the steps needed to run locally at the time of writing

- Open file generate-ccd-defination.sh.  Amend the line that says:
```shell
docker run --pull always --user $UID --rm --name json2xlsx \
``` 
to

```shell
docker run --pull always --rm --name json2xlsx \
```
(remove --user $UID)

- Then build
```shell
gradle build
```
- Then login to the subscription. Get the subscription id from another dev
```shell
az acr login --name hmctspublic --subscription [SUBSCRIPTION ID]
```

Then run
```shell
./gradlew bootWithCcd
```

Also metics link to readme returns 404. So consider fixing or removing

**Comment by hfilmore** [comment]
generate-ccd-defination.sh is found in bin/
"gradle build" should = ./gradlew build

**Comment by hfilmore** [comment]
https://github.com/hmcts/adoption-cos-api/pull/915

**Comment by hfilmore** [comment]
Changes deployed.
